publisher_forward_position_controller:
  ros__parameters:

    controller_name: "forward_position_controller"
    wait_sec_between_publish: 2

    goal_names: ["pos1", "pos2", "pos3", "pos4"]
    pos1: [0.0, 3.1, 0.0, 0.0, 0.0, 0.0]
    pos2: [0.0, 3.0, 0.1, 0.4, 0.0, 3.0]
    pos3: [0.0, 2.9, 0.2, 0.6, 0.0, 3.0]
    pos4: [0.0, 2.9, 0.5, 0.8, 0.0, 3.0]

publisher_joint_trajectory_controller:
  ros__parameters:

    controller_name: "joint_trajectory_controller"
    wait_sec_between_publish: 2
    repeat_the_same_goal: 1 # useful to simulate continuous inputs

    goal_time_from_start: 3.0
    goal_names: ["pos1", "pos2", "pos3", "pos4"]
    pos1:
      positions: [0.0, 3.1, 0.0, 0.0, 0.0, 0.0]
    pos2:
      positions: [0.0, 3.0, 0.1, 0.4, 0.0, 3.0]
    pos3:
      positions: [0.0, 2.9, 0.2, 0.6, 0.0, 3.0]
    pos4:
      positions: [0.0, 2.9, 0.5, 0.8, 0.0, 3.0]

    joints:
      - joint_1
      - joint_2
      - joint_3
      - joint_4
      - joint_5
      - joint_6