<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

  <xacro:macro name="manipulator_description" params="
               lower_joint_limit:=^|${-pi/2}
               upper_joint_limit:=^|${pi/2}
               fix_link_to_robot_base:=^|false"
  >

  <!-- helper macro -->
  <xacro:include filename="$(find guardian_description)/urdf/core/create_link.xacro"/>

  <!-- Links -->
  <xacro:property name="link0_len" value="0.0793" />
  <xacro:property name="link1_len" value="0.03" />
  <xacro:property name="link2_len" value="0.127" />
  <xacro:property name="link3_len" value="0.18415" />
  <xacro:property name="link4_len" value="0.0635" />
  <xacro:property name="link5_len" value="0.1143" />

  <xacro:create_link
    link_name="manipulator_base_link"
    color="green"
    xyz_offset="0 0 ${link0_len/2}"
    rpy_offset="0 0 0"
    z="${link0_len}"
    x="0.0285"
    y="0.0285"
  />

  <xacro:create_link
    link_name="link_1"
    color="blue"
    xyz_offset="0 0 ${link1_len/2}"
    rpy_offset="0 0 0"
    z="${link1_len}"
    x="0.0285"
    y="0.035"
  />

  <xacro:create_link
    link_name="link_2"
    color="red"
    xyz_offset="0 0 ${link2_len/2}"
    rpy_offset="0 0 0"
    z="${link2_len}"
    x="0.0285"
    y="0.035"
  />

  <xacro:create_link
    link_name="link_3"
    color="grey"
    xyz_offset="0 0 ${link3_len/2}"
    rpy_offset="0 0 0"
    z="${link3_len}"
    x="0.0285"
    y="0.035"
  />

  <xacro:create_link
    link_name="link_4"
    color="red"
    xyz_offset="0 0 ${link4_len/2}"
    rpy_offset="0 0 0"
    z="${link4_len}"
    x="0.0285"
    y="0.035"
  />

  <xacro:create_link
    link_name="link_5"
    color="blue"
    xyz_offset="0 0 ${link5_len/2}"
    rpy_offset="0 0 0"
    z="${link5_len}"
    x="0.0285"
    y="0.035"
  />

  <!-- Joints -->
  <joint name="base_joint" type="fixed">
    <xacro:if value="${fix_link_to_robot_base}">
      <parent link="base_link"/>
      <origin xyz="0 0 0.05" rpy="0 0 0"/>
    </xacro:if>
    <xacro:unless value="${fix_link_to_robot_base}">
      <parent link="world"/>
      <origin xyz="0 0 0" rpy="0 0 0"/>
    </xacro:unless>
    <child link="manipulator_base_link"/>
    <axis xyz="0 0 1"/>
  </joint>

  <joint name="joint_1" type="revolute">
    <parent link="manipulator_base_link"/>
    <child link="link_1"/>
    <origin xyz="0 0 ${link0_len}" rpy="0 0 0"/>
    <axis xyz="0 0 1"/>
    <limit effort="1000.0" lower="${lower_joint_limit}" upper="${upper_joint_limit}" velocity="2.5"/>
  </joint>

  <joint name="joint_2" type="revolute">
    <parent link="link_1"/>
    <child link="link_2"/>
    <origin xyz="0 0 ${link1_len}" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
    <limit effort="1000.0" lower="${lower_joint_limit}" upper="${upper_joint_limit}" velocity="2.5"/>
  </joint>

  <joint name="joint_3" type="revolute">
    <parent link="link_2"/>
    <child link="link_3"/>
    <origin xyz="0 0 ${link2_len}" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
    <limit effort="1000.0" lower="${lower_joint_limit}" upper="${upper_joint_limit}" velocity="2.5"/>
  </joint>

  <joint name="joint_4" type="revolute">
    <parent link="link_3"/>
    <child link="link_4"/>
    <origin xyz="0 0 ${link3_len}" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
    <limit effort="1000.0" lower="${lower_joint_limit}" upper="${upper_joint_limit}" velocity="2.5"/>
  </joint>

  <joint name="joint_5" type="revolute">
    <parent link="link_4"/>
    <child link="link_5"/>
    <origin xyz="0 0 ${link4_len}" rpy="0 0 0"/>
    <axis xyz="0 0 1"/>
    <limit effort="1000.0" lower="${lower_joint_limit}" upper="${upper_joint_limit}" velocity="2.5"/>
  </joint>

</xacro:macro>

</robot>
